line-length = 90
indent-width = 4

target-version = "py310"
extend-include = ["*.ipynb", "*.md"]

[lint]
select = ["F", "E", "W", "I001", "I002"]

[format]

# pycodestyle "E" "W",
# Pyflakes "F",
# pyupgrade "UP",
# flake8-bugbear "B",
# flake8-simplify "SIM",
# isort "I",
